name: Test PR

on:
  push:
    branches: [ "1.12.2", "1.14.4", "1.15.2", "1.20.x" ]
    types: ["closed"]
  pull_request:
    branches: [ "1.12.2", "1.14.4", "1.15.2", "1.20.x" ]
    types: ["closed"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install
        run: |
          sudo apt install openjdk-17-jdk
          export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
          sudo chmod +x gradlew

      - name: Test
        run: |
          ./gradlew
          ./gradlew test > testResult.txt
          cat testResults.txt
          
          if  grep -q "FAILED" testResult.txt then
              echo "Tests failed"
              exit 1
          else
            if  grep -q "BUILD SUCCESSFUL" testResult.txt then
                echo "Tests Passed"
                exit 1
            else
                echo "unexpected behavior"
            fi
          fi
